version: '3.8'

services:
  front:
    build:
      context: ./Docker/Frontend
    image: front
    container_name: front
    depends_on:
      - back
    env_file:
      - .env
    volumes:
      - ft_transcendence_front_vol:/app
    ports:
      - 3000:3000
    networks:
      - transcendence
    restart: always

  back:
    build:
      context: ./Docker/Backend
    image: back
    container_name: back
    depends_on:
      - database
    env_file:
      - .env
    volumes:
      - ft_transcendence_back_vol:/app
    ports:
      - 4000:4000
      - 5555:5555
    networks:
      - transcendence
    restart: always

  database:
    image: postgres
    container_name: database
    volumes:
      - ft_transcendence_database_vol:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - transcendence
    restart: always

volumes:
  ft_transcendence_front_vol:
    driver: local
    driver_opts:
      device: ${PWD}/App/Next
      o: bind
      type: none

  ft_transcendence_back_vol:
    driver: local
    driver_opts:
      device: ${PWD}/App/Nest
      o: bind
      type: none

  ft_transcendence_database_vol:

networks:
  transcendence:
    driver: bridge
    name: transcendence
