version: '3.7'

services:
  frontend:
    build:
      context: ./Frontend
    image: front_react
    container_name: front_react
    depends_on:
      - backend 
    volumes:
      - frontend_vol:/app
    ports: 
      - 3000:3000
    networks:
      - transcendence
    restart: always

  backend:
    build:
      context: ./Backend
    image: back_nest
    container_name: back_nest
    depends_on:
      - database
    volumes:
      - backend_vol:/app
    ports: 
      - 4000:4000
    networks:
      - transcendence
    restart: always

  database:
    image: postgres
    container_name: db_postgres
    volumes:
      - database_vol:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - transcendence
    restart: always

volumes:

  frontend_vol:
    driver: local
    driver_opts:
      device: ../Frontend
      o: bind
      type: none

  backend_vol:
    driver: local
    driver_opts:
      device: ../Backend
      o: bind
      type: none
  
  database_vol:

networks:
  transcendence:
    driver: bridge
    name: transcendence
