version: '3.7'

services:
  frontend:
    build:
      context: ./Frontend
    image: front_react
    container_name: front_react
    volumes:
      - frontend_vol:/app
    ports: 
      - 3000:3000
    networks:
      - transcendence
    restart: always

  backend:
    build:
      context: ./Backend
    image: back_nest
    container_name: back_nest
    volumes:
      - backend_vol:/app
    ports: 
      - 4000:4000
    networks:
      - transcendence
    restart: always

volumes:

  frontend_vol:
    driver: local
    driver_opts:
      device: ../Frontend
      o: bind
      type: none

  backend_vol:
    driver: local
    driver_opts:
      device: ../Backend
      o: bind
      type: none

networks:
  transcendence:
    driver: bridge
    name: transcendence
