name: Branch name check

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Extract branch name
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_ENV

      - name: Check branch name
        run: |
          branchName="${{ env.branch }}"
          
          if [[ ! $branchName =~ ^FT-[0-9]+-[a-zA-Z0-9-]+$ ]]; then
            echo "Invalid branch name '${branchName}'. It doesn't match a JIRA issue"
            exit 1
          fi

