name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - name: Launch Docker Compose
        uses: adambirds/docker-compose-action@v1.3.0
        with:
          compose-file: "docker-compose.yml"
          test-container: "back"
          test-command: |
            cd nest_app
            npm run test

