name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up environment variables
        run: echo "$ENV_VARS" > .env
        env:
          ENV_VARS: ${{ secrets.ENV_VARS }}

      - name: Launch Docker Compose
        run: |
<<<<<<< HEAD
          docker-compose -f docker-compose.yml up -d
          docker exec back sh -c 'cd nest_app && npm run test'
        env:
          ENV_VARS: ${{ secrets.ENV_VARS }}
=======
          make
        env:
          ENV_VARS: ${{ secrets.ENV_VARS }}
        
      - name: Check running containers
        run: make ls
        
      - name: Inspecting database container logs
        run: docker logs database
        
      - name: Accessing back container
        run: docker exec back sh 
      
      - name: Moving to nest_app
        run: cd nest_app
        
      - name: Launching test
        run: npm run test

>>>>>>> 0441d09819509defb3a9001ea9b12a91e3dd38e9
