name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up environment variables
        run: echo "$ENV_VARS" > .env
        env:
          ENV_VARS: ${{ secrets.ENV_VARS }}

      - name: Launch Docker Compose
        uses: adambirds/docker-compose-action@v1.3.0
        with:
          compose-file: "docker-compose.yml"
          test-container: "back"
          test-command: |
            sh -c 'find /app -type d -name "nest_app" -execdir npm run test \;'
        env:
          ENV_VARS: ${{ secrets.ENV_VARS }}
