name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest
    # env:
    #   FRONT_PORT: ${{ secrets.FRONT_PORT }}
    #   BACK_PORT: ${{ secrets.BACK_PORT }}
    #   DB_PORT: ${{ secrets.DB_PORT }}
    #   POSTGRES_USER:  ${{ secrets.POSTGRES_USER }}
    #   POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
    #   POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
    #   DATABASE_CONTAINER_NAME: ${{ secrets.DATABASE_CONTAINER_NAME }}

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up environment variables
        run: |
          touch .env
          echo FRONT_PORT=${{ secrets.FRONT_PORT }} >> .env
          echo BACK_PORT=${{ secrets.BACK_PORT }} >> .env
          echo DB_PORT=${{ secrets.DB_PORT }} >> .env
          echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} >> .env
          echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env
          echo POSTGRES_DB=${{ secrets.POSTGRES_DB }} >> .env
          echo DATABASE_CONTAINER_NAME=${{ secrets.DATABASE_CONTAINER_NAME }} >> .env
          echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env
          echo URL_ARGUMENTS=${{ secrets.URL_ARGUMENTS }} >> .env
          echo LOCAL_IP=${{ secrets.LOCAL_IP }} >> .env
          cat .env
        
      - name: Launch Docker Compose
        run: make
        
      - name: Check running containers
        run: make ls
        
      - name: Inspecting database container logs
        run: docker logs database
        
      - name: Accessing back container
        run: docker exec -it back sh 
      
      - name: Moving to nest_app
        run: cd nest_app
        
      - name: Launching test
        run: npm run test
